### ISSUE TITLE
Missing TemplateEditor Project

### ISSUE THREAD

**Issue by HoundComp** [akhtn7/AddTextToImage#1]
I have just downloaded the project and I see the TemplateEditor project is not in the solution or on github.

**Comment by akhtn7** [comment]
TemplateEditor – is a WinForm project and I used it to create templates and image galleries. The solution works without it, however you will not able to create new templates. I didn’t publish it on github because it was made quickly and only for me (I mean without following patterns).

**Comment by HoundComp** [comment]
I understand. Would you mind sharing it with me though so I could understand more easily how you created the templates with it? I am looking to do more with this and trying to learn all I can from it. I could give you my email if that would help.

**Comment by akhtn7** [comment]
I've added TemplateEditor Project to the solution. Once more, it was done only for me and I have not finished it: some features don't work or not implemented. For example, I've copied font files to the solution and then manually added them into table in the database. So, some operations have to be done manually. 

To work with TemplateEditor you need to set correct path to database files in connectionString in App.config.  Also, it would be better if you move files: AddTextToImage.mdf and AddTextToImage_log.ldf to untracked. Some github clients prevent exclusive access of SQL server to these files.

**Comment by HoundComp** [comment]
Thanks, much appreciated.
